### ISSUE TITLE
Error starting server!

### ISSUE THREAD

**Issue by lisindima** [tristanratz/ChatApp#1]
Hi, I can’t start the server, I tried macOS Catalina with Python 3.7.4 and on Windows 10 with 3.8.0. The error is the same.
<img width="564" alt="Снимок экрана 2019-10-23 в 13 51 20" src="https://user-images.githubusercontent.com/43087859/67365846-a09f2b80-f59c-11e9-8095-08a581704a72.png">

**Comment by tristanratz** [comment]
Hey lisindima,
I issued a fix that should solve the problem.

Thank you,
Tristan
