### ISSUE TITLE
Fatal error while chat window appears

### ISSUE THREAD

**Issue by lisindima** [tristanratz/ChatApp#2]
Hi, the server starts successfully, the client sees it and connects successfully, but after entering the username this happens:

<img width="1280" alt="Снимок экрана 2019-10-24 в 12 54 49" src="https://user-images.githubusercontent.com/43087859/67457467-eec83380-f65d-11e9-9c8b-b5979d61a25e.png">
<img width="1280" alt="Снимок экрана 2019-10-24 в 12 54 40" src="https://user-images.githubusercontent.com/43087859/67457469-ef60ca00-f65d-11e9-99ef-41a361854f74.png">
<img width="372" alt="Снимок экрана 2019-10-24 в 12 54 24" src="https://user-images.githubusercontent.com/43087859/67457470-ef60ca00-f65d-11e9-93ca-7581368e1779.png">
<img width="1280" alt="Снимок экрана 2019-10-24 в 12 54 11" src="https://user-images.githubusercontent.com/43087859/67457471-ef60ca00-f65d-11e9-821f-5195a971126b.png">

Upon your request I will provide any additional data! I note that for the first time I managed to successfully connect and even leave a couple of messages. But after connecting the second device, an error occurred! When you restart, the error repeats immediately after entering a nickname!

**Comment by tristanratz** [comment]
Thank you for the report. I tried to reproduce the crash in Xcode 11.1 but it seemed to work work fine with even more than two agents. I'm looking into that issue and inform you as soon as I have a solution

**Comment by tristanratz** [comment]
Hey, on my 13.2 device I had the same issue. I think that one animation made some problems. I removed it and hope that it will work now for you. Let me know if you still encounter the problem

**Comment by lisindima** [comment]
Thanks for the corrections, everything works fine!
